// @vitest-environment jsdom
import { act, cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
const mocks = vi.hoisted(() => ({ get: vi.fn(), save: vi.fn(), dismiss: vi.fn(), credentials: vi.fn(), revoke: vi.fn(), error: vi.fn(), success: vi.fn(), warning: vi.fn() }))
vi.mock('@/actions/secrets', () => ({ getSecretRequests: mocks.get, saveSecret: mocks.save, dismissSecretRequest: mocks.dismiss, getProjectCredentials: mocks.credentials, revokeProjectCredential: mocks.revoke }))
vi.mock('sonner', () => ({ toast: { error: mocks.error, success: mocks.success, warning: mocks.warning } }))
import { SecretsCard } from './secrets-card'
const projectId = '11111111-1111-4111-8111-111111111111'
const request = { id: '22222222-2222-4222-8222-222222222222', name: 'PAYMENT_API_KEY', description: 'Cobrar no backend', target: 'supabase', environment: 'development', targetRef: 'projectref', status: 'pending' }
const credential = { id: '55555555-5555-4555-8555-555555555555', name: 'RESEND_API_KEY', environment: 'development', createdAt: '2026-09-24T10:00:00Z', updatedAt: '2026-09-24T10:00:00Z' }
beforeEach(() => { vi.resetAllMocks(); mocks.get.mockResolvedValue({ requests: [request] }); mocks.save.mockResolvedValue({ ok: true }); mocks.dismiss.mockResolvedValue({ ok: true }); mocks.credentials.mockResolvedValue({ credentials: [] }); mocks.revoke.mockResolvedValue({ ok: true }) })
afterEach(() => { cleanup(); vi.useRealTimers() })
describe('project secret form', () => {
  it('shows an exact accessible name, a masked field, reason and the pinned target/environment', async () => {
    render(<SecretsCard projectId={projectId} />)
    const field = await screen.findByLabelText('PAYMENT_API_KEY') as HTMLInputElement
    expect(field.getAttribute('type')).toBe('password')
    expect(field.getAttribute('name')).toBe('PAYMENT_API_KEY')
    expect(screen.getByText('Cobrar no backend')).toBeTruthy()
    expect(screen.getByText('Supabase · Edge Functions · Desenvolvimento · projectref')).toBeTruthy()
    expect(document.getElementById('secrets')).toBeTruthy()
  })
  it('submits the bound request with the storage preference, then clears the field after confirmed success', async () => {
    render(<SecretsCard projectId={projectId} />)
    const field = await screen.findByLabelText('PAYMENT_API_KEY') as HTMLInputElement
    fireEvent.change(field, { target: { value: 'private-value' } })
    fireEvent.click(screen.getByRole('button', { name: 'Salvar no Supabase' }))
    await waitFor(() => expect(mocks.save).toHaveBeenCalledWith({ projectId, requestId: request.id, value: 'private-value', remember: true }))
    await waitFor(() => expect(field.value).toBe(''))
    expect(JSON.stringify(mocks.success.mock.calls)).not.toContain('private-value')
  })
  it('keeps the draft and re-enables saving after rejection or an unexpected transport error', async () => {
    mocks.save.mockRejectedValue(new Error('transport'))
    render(<SecretsCard projectId={projectId} />)
    const field = await screen.findByLabelText('PAYMENT_API_KEY') as HTMLInputElement; fireEvent.change(field, { target: { value: 'private-value' } })
    fireEvent.click(screen.getByRole('button', { name: 'Salvar no Supabase' }))
    await waitFor(() => expect(mocks.error).toHaveBeenCalled())
    expect(field.value).toBe('private-value'); expect(field.disabled).toBe(false)
    mocks.save.mockResolvedValue({ error: 'Conexão indisponível.' })
    fireEvent.click(screen.getByRole('button', { name: 'Salvar no Supabase' }))
    await waitFor(() => expect(mocks.error).toHaveBeenCalledWith('Conexão indisponível.'))
    expect(field.value).toBe('private-value')
  })
  it('preserves multiline credentials pasted into a generic integration field', async () => {
    render(<SecretsCard projectId={projectId} />)
    const field = await screen.findByLabelText('PAYMENT_API_KEY')
    const credential = '{\n  "fixture": "private-value"\n}'
    fireEvent.paste(field, { clipboardData: { getData: () => credential } })
    expect((screen.getByLabelText('PAYMENT_API_KEY') as HTMLInputElement).value).not.toContain('private-value')
    expect(screen.getByText(/Credencial com várias linhas recebida/)).toBeTruthy()
    fireEvent.click(screen.getByRole('button', { name: 'Salvar no Supabase' }))
    await waitFor(() => expect(mocks.save).toHaveBeenCalledWith({ projectId, requestId: request.id, value: credential, remember: true }))
  })
  it('shows refresh failures and supports retry without discarding an existing draft', async () => {
    render(<SecretsCard projectId={projectId} />)
    const field = await screen.findByLabelText('PAYMENT_API_KEY') as HTMLInputElement; fireEvent.change(field, { target: { value: 'draft' } })
    mocks.get.mockResolvedValueOnce({ error: 'Pedidos indisponíveis.' })
    fireEvent(window, new Event('focus'))
    expect((await screen.findByRole('alert')).textContent).toContain('Pedidos indisponíveis.')
    expect(field.value).toBe('draft')
    fireEvent.click(screen.getByRole('button', { name: 'Tentar novamente' }))
    await waitFor(() => expect(screen.queryByRole('alert')).toBeNull())
    expect(field.value).toBe('draft')
  })
  it('keeps missing schema visible and reveals the named field after the platform database recovers', async () => {
    mocks.get.mockResolvedValueOnce({ error: 'A estrutura dos pedidos de chaves não está disponível no banco do Supremo.', errorCode: 'schema_unavailable' })
    render(<SecretsCard projectId={projectId} />)
    expect((await screen.findByRole('alert')).textContent).toContain('banco do Supremo')
    expect(screen.queryByPlaceholderText('Cole a chave')).toBeNull()
    expect(screen.queryByText('configurado')).toBeNull()
    fireEvent.click(screen.getByRole('button', { name: 'Tentar novamente' }))
    expect(await screen.findByLabelText('PAYMENT_API_KEY')).toBeTruthy()
    expect(screen.queryByRole('alert')).toBeNull()
    expect(mocks.save).not.toHaveBeenCalled()
  })
  it('polls new requests into an already open page and preserves pending field content', async () => {
    vi.useFakeTimers()
    render(<SecretsCard projectId={projectId} />)
    await act(async () => { await Promise.resolve() })
    const field = screen.getByLabelText('PAYMENT_API_KEY') as HTMLInputElement; fireEvent.change(field, { target: { value: 'draft' } })
    mocks.get.mockResolvedValue({ requests: [request, { ...request, id: 'another', name: 'MAIL_API_KEY', target: 'vercel', environment: 'preview' }] })
    await act(async () => { await vi.advanceTimersByTimeAsync(5000) })
    expect(screen.getByLabelText('MAIL_API_KEY').getAttribute('type')).toBe('password')
    expect(field.value).toBe('draft')
    expect(screen.getByRole('button', { name: 'Salvar no Vercel' })).toBeTruthy()
  })
  it('does not offer a fillable field for an old request without a bound destination', async () => {
    mocks.get.mockResolvedValue({ requests: [{ ...request, target: null, targetRef: null, environment: null }] })
    render(<SecretsCard projectId={projectId} />)
    expect(await screen.findByText(/Pedido antigo sem destino confirmado/)).toBeTruthy()
    expect(screen.queryByPlaceholderText('Cole a chave')).toBeNull()
    fireEvent.click(screen.getByRole('button', { name: 'Dispensar pedido PAYMENT_API_KEY' }))
    await waitFor(() => expect(mocks.dismiss).toHaveBeenCalledWith({ projectId, requestId: request.id }))
  })
  it('shows fulfilled state and hides the previous value input', async () => {
    mocks.get.mockResolvedValue({ requests: [{ ...request, status: 'fulfilled' }] })
    render(<SecretsCard projectId={projectId} />)
    expect(await screen.findByText('configurado')).toBeTruthy()
    expect(screen.queryByPlaceholderText('Cole a chave')).toBeNull()
    expect(screen.getByText(/Não é necessário preencher novamente no painel do provedor/)).toBeTruthy()
  })
  it('applies SMTP from one private field and shows the sender before submission', async () => {
    mocks.get.mockResolvedValue({ requests: [{ ...request, configuration: { kind: 'supabase-smtp', provider: 'resend', senderEmail: 'login@example.com', senderName: 'Example' } }] })
    render(<SecretsCard projectId={projectId} />)
    const field = await screen.findByLabelText('Chave da API do Resend') as HTMLInputElement
    expect(field.type).toBe('password')
    expect(screen.getByText(/Remetente: Example/).textContent).toContain('login@example.com')
    fireEvent.change(field, { target: { value: 'synthetic-private-key' } })
    fireEvent.click(screen.getByRole('button', { name: 'Configurar email' }))
    await waitFor(() => expect(mocks.save).toHaveBeenCalledWith({ projectId, requestId: request.id, value: 'synthetic-private-key', remember: true }))
    await waitFor(() => expect(field.value).toBe(''))
    expect(mocks.success).toHaveBeenCalledWith('Configuração de email salva no Supabase. O envio ainda precisa ser testado.')
  })
  it('identifies the selected development user and submits the password only to the owner action', async () => {
    const userId = '44444444-4444-4444-8444-444444444444'
    mocks.get.mockResolvedValue({ requests: [{ ...request, configuration: { kind: 'supabase-user-password', userId } }] })
    render(<SecretsCard projectId={projectId} />)
    const field = await screen.findByLabelText('Nova senha de desenvolvimento') as HTMLInputElement
    expect(screen.getByText(`Senha de desenvolvimento · Usuário ${userId} · projectref`)).toBeTruthy()
    expect(field.type).toBe('password')
    expect(screen.queryByRole('checkbox')).toBeNull()
    fireEvent.change(field, { target: { value: 'synthetic-password' } })
    fireEvent.click(screen.getByRole('button', { name: 'Definir senha' }))
    await waitFor(() => expect(mocks.save).toHaveBeenCalledWith({ projectId, requestId: request.id, value: 'synthetic-password', remember: false }))
    await waitFor(() => expect(field.value).toBe(''))
    expect(JSON.stringify(mocks.success.mock.calls)).not.toContain('synthetic-password')
  })
  it('lets the owner opt out of storing a credential while still configuring the destination', async () => {
    render(<SecretsCard projectId={projectId} />)
    const field = await screen.findByLabelText('PAYMENT_API_KEY')
    const checkbox = screen.getByRole('checkbox', { name: 'Guardar no cofre deste projeto para reutilizar' }) as HTMLInputElement
    expect(checkbox.checked).toBe(true)
    fireEvent.click(checkbox)
    fireEvent.change(field, { target: { value: 'one-time-value' } })
    fireEvent.click(screen.getByRole('button', { name: 'Salvar no Supabase' }))
    await waitFor(() => expect(mocks.save).toHaveBeenCalledWith({ projectId, requestId: request.id, value: 'one-time-value', remember: false }))
    expect(mocks.success).not.toHaveBeenCalledWith('Credencial guardada no cofre deste projeto para reutilizar.')
  })
  it('clears an applied credential even if vault storage fails, without claiming it was stored', async () => {
    mocks.save.mockResolvedValue({ ok: true, warning: 'Configuração aplicada, mas não foi possível guardar a credencial no cofre.', credentialSaved: false })
    render(<SecretsCard projectId={projectId} />)
    const field = await screen.findByLabelText('PAYMENT_API_KEY') as HTMLInputElement
    fireEvent.paste(field, { clipboardData: { getData: () => 'private-line\nprivate-line-two' } })
    fireEvent.click(screen.getByRole('button', { name: 'Salvar no Supabase' }))
    await waitFor(() => expect(field.value).toBe(''))
    expect(screen.queryByText(/Credencial com várias linhas recebida/)).toBeNull()
    expect(mocks.warning).toHaveBeenCalledWith('Configuração aplicada, mas não foi possível guardar a credencial no cofre.')
    expect(mocks.success).toHaveBeenCalledWith('PAYMENT_API_KEY enviado às Edge Functions do projeto.')
    expect(mocks.success).not.toHaveBeenCalledWith('Credencial guardada no cofre deste projeto para reutilizar.')
    expect(mocks.error).not.toHaveBeenCalled()
    expect(JSON.stringify([...mocks.success.mock.calls, ...mocks.warning.mock.calls])).not.toContain('private-line')
  })
  it('confirms vault storage only when the server attests it and refreshes its metadata', async () => {
    mocks.save.mockResolvedValue({ ok: true, credentialSaved: true })
    render(<SecretsCard projectId={projectId} />)
    const field = await screen.findByLabelText('PAYMENT_API_KEY')
    await waitFor(() => expect(mocks.credentials).toHaveBeenCalledTimes(1))
    mocks.credentials.mockResolvedValue({ credentials: [credential] })
    fireEvent.change(field, { target: { value: 'stored-value' } })
    fireEvent.click(screen.getByRole('button', { name: 'Salvar no Supabase' }))
    expect(await screen.findByText('RESEND_API_KEY')).toBeTruthy()
    expect(mocks.success).toHaveBeenCalledWith('Credencial guardada no cofre deste projeto para reutilizar.')
    expect(document.body.textContent).not.toContain('stored-value')
  })
  it('shows stored metadata without pending requests and removes only the vault reference', async () => {
    mocks.get.mockResolvedValue({ requests: [] })
    mocks.credentials.mockResolvedValue({ credentials: [credential] })
    render(<SecretsCard projectId={projectId} />)
    expect(await screen.findByText('Cofre deste projeto')).toBeTruthy()
    expect(screen.getByText('RESEND_API_KEY')).toBeTruthy()
    expect(screen.getByText('Desenvolvimento')).toBeTruthy()
    expect(screen.getByText(/não revoga a chave nem desfaz configurações no provedor/)).toBeTruthy()
    expect(screen.queryByPlaceholderText('Cole a chave')).toBeNull()
    mocks.credentials.mockResolvedValue({ credentials: [] })
    fireEvent.click(screen.getByRole('button', { name: 'Remover RESEND_API_KEY de Desenvolvimento do cofre' }))
    await waitFor(() => expect(mocks.revoke).toHaveBeenCalledWith({ projectId, credentialId: credential.id }))
    await waitFor(() => expect(screen.queryByText('RESEND_API_KEY')).toBeNull())
    expect(mocks.success).toHaveBeenCalledWith('Credencial removida do cofre. As configurações no provedor foram mantidas.')
    expect(mocks.dismiss).not.toHaveBeenCalled()
  })
  it('keeps stored metadata when removal is rejected and allows retry after a transport error', async () => {
    mocks.get.mockResolvedValue({ requests: [] })
    mocks.credentials.mockResolvedValue({ credentials: [credential] })
    mocks.revoke.mockResolvedValueOnce({ error: 'Não foi possível remover do cofre.' }).mockRejectedValueOnce(new Error('transport'))
    render(<SecretsCard projectId={projectId} />)
    const remove = await screen.findByRole('button', { name: 'Remover RESEND_API_KEY de Desenvolvimento do cofre' }) as HTMLButtonElement
    fireEvent.click(remove)
    await waitFor(() => expect(mocks.error).toHaveBeenCalledWith('Não foi possível remover do cofre.'))
    expect(screen.getByText('RESEND_API_KEY')).toBeTruthy()
    expect(remove.disabled).toBe(false)
    fireEvent.click(remove)
    await waitFor(() => expect(mocks.error).toHaveBeenCalledWith('Não foi possível remover a credencial do cofre. Tente novamente.'))
    expect(remove.disabled).toBe(false)
    expect(mocks.success).not.toHaveBeenCalled()
  })
  it('reports vault metadata fetch errors without discarding a pending secret draft', async () => {
    render(<SecretsCard projectId={projectId} />)
    const field = await screen.findByLabelText('PAYMENT_API_KEY') as HTMLInputElement
    await waitFor(() => expect(mocks.credentials).toHaveBeenCalledTimes(1))
    fireEvent.change(field, { target: { value: 'draft' } })
    mocks.credentials.mockRejectedValueOnce(new Error('transport'))
    fireEvent(window, new Event('focus'))
    expect((await screen.findByRole('alert')).textContent).toContain('Não foi possível atualizar o cofre deste projeto')
    expect(field.value).toBe('draft')
    mocks.credentials.mockResolvedValueOnce({ error: 'Cofre temporariamente indisponível.' })
    fireEvent.click(screen.getByRole('button', { name: 'Tentar novamente' }))
    await waitFor(() => expect(screen.getByRole('alert').textContent).toContain('Cofre temporariamente indisponível.'))
    fireEvent.click(screen.getByRole('button', { name: 'Tentar novamente' }))
    await waitFor(() => expect(screen.queryByRole('alert')).toBeNull())
    expect(field.value).toBe('draft')
  })
  it('ignores a stale metadata response after switching projects and clears old drafts immediately', async () => {
    let resolveCredentials: (value: { credentials: typeof credential[] }) => void = () => { throw new Error('not initialized') }
    mocks.credentials.mockImplementationOnce(() => new Promise<{ credentials: typeof credential[] }>((resolve) => { resolveCredentials = resolve }))
    const { rerender } = render(<SecretsCard projectId={projectId} />)
    const field = await screen.findByLabelText('PAYMENT_API_KEY')
    fireEvent.change(field, { target: { value: 'old-project-draft' } })
    await waitFor(() => expect(mocks.credentials).toHaveBeenCalledTimes(1))
    const nextProjectId = '99999999-9999-4999-8999-999999999999'
    mocks.get.mockResolvedValue({ requests: [] })
    rerender(<SecretsCard projectId={nextProjectId} />)
    expect(screen.queryByLabelText('PAYMENT_API_KEY')).toBeNull()
    await waitFor(() => expect(mocks.credentials).toHaveBeenCalledWith(nextProjectId))
    await act(async () => { resolveCredentials({ credentials: [credential] }) })
    expect(screen.queryByText('RESEND_API_KEY')).toBeNull()
    expect(document.getElementById('secrets')).toBeNull()
  })
})
