import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { buildProjectFiles, TEMPLATE_VERSION } from '../src/lib/templates/project-files'
import { blobHash, lockEntryHash, type ValidationManifest } from '../packages/cli/src/validation-integrity'

const protectedPaths = [
  '.github/workflows/ci.yml', 'scripts/security-audit.js', 'scripts/verify.mjs',
  'scripts/acceptance-rls.mjs', 'scripts/rls-isolation-inventory.mjs',
  'scripts/rls-isolation-reporter.mjs', 'scripts/rls-isolation-gate.mjs',
  'supabase/isolation.ts', 'vitest.config.ts', 'vitest.setup.ts',
  'playwright.config.ts', 'e2e/smoke.spec.ts', 'eslint.config.mjs', 'tsconfig.json',
]
const protectedScripts = ['typecheck', 'lint', 'test', 'test:coverage', 'test:rls', 'test:e2e',
  'audit:security', 'build', 'verify', 'verify:quick', 'verify:security', 'verify:full', 'security:audit']
const manifests: ValidationManifest[] = []
for (const kind of ['public', 'solo', 'team'] as const) {
  const files = buildProjectFiles({ projectName: 'supremo-policy', description: '', kind })
  const contents = new Map(files.map(file => [file.path, file.content]))
  const pkg = JSON.parse(contents.get('package.json')!) as { scripts: Record<string, string>; devDependencies: Record<string, string> }
  const lock = JSON.parse(contents.get('package-lock.json')!) as { packages: Record<string, unknown> }
  manifests.push({
    version: TEMPLATE_VERSION, kind,
    files: Object.fromEntries(protectedPaths.map(path => {
      const content = contents.get(path)
      if (content === undefined) throw new Error(`Missing policy file: ${path}`)
      return [path, blobHash(content)]
    })),
    scripts: Object.fromEntries(protectedScripts.map(name => {
      const value = pkg.scripts[name]
      if (!value) throw new Error(`Missing policy script: ${name}`)
      return [name, value]
    })),
    devDependencies: pkg.devDependencies,
    lock: Object.fromEntries(Object.entries(lock.packages).filter(([path]) => path !== '').map(([path, value]) => [path, lockEntryHash(value)])),
  })
}
const target = 'packages/cli/src/generated/validation-policy.ts'
// Keep package names separate from digest fields: names such as js-tokens are
// public package identifiers, not credential keys. Tuples remain plain/auditable
// and avoid representing these public hashes as apparent API-key assignments.
const entries = manifests.map(manifest => ({ ...manifest, lock: Object.entries(manifest.lock) }))
const source = `// Generated by scripts/generate-validation-policy.mts. Authority: engine release.\nimport type { ValidationManifest } from '../validation-integrity'\nexport const TRUSTED_VALIDATION_POLICIES: readonly ValidationManifest[] = ${JSON.stringify(entries, null, 2)}.map(policy => ({ ...policy, lock: Object.fromEntries(policy.lock) }))\n`
if (process.argv.includes('--check')) {
  if (readFileSync(target, 'utf8') !== source) throw new Error('Validation manifest is stale. Regenerate before building the CLI.')
} else {
  mkdirSync('packages/cli/src/generated', { recursive: true })
  writeFileSync(target, source)
}
