import { describe, expect, it } from 'vitest'
import { acceptanceArchive, acceptanceFixture } from '@/test/fixtures/acceptance'
import { acceptanceMatchesObservation, acceptanceReportSchema, MAX_ACCEPTANCE_ARCHIVE_BYTES, readAcceptanceArchive } from './acceptance'
import { buildValidationFeedback, validationFeedbackSchema } from './feedback'

describe('bounded acceptance archive parser', () => {
  it.each([true, false])('decodes independent ZIP fixture (compressed=%s) without extracting files', (compressed) => {
    expect(readAcceptanceArchive(acceptanceArchive(compressed))).toEqual(acceptanceFixture)
  })
  it('accepts the data-descriptor form generated by streaming ZIP writers', () => {
    const archive = acceptanceArchive()
    const directory = archive.readUInt32LE(archive.length - 6)
    const descriptor = Buffer.alloc(16)
    descriptor.writeUInt32LE(0x08074b50)
    archive.copy(descriptor, 4, directory + 16, directory + 28)
    archive.writeUInt16LE(8, 6); archive.writeUInt16LE(8, directory + 8)
    archive.writeUInt32LE(directory + 16, archive.length - 6)
    expect(readAcceptanceArchive(Buffer.concat([archive.subarray(0, directory), descriptor, archive.subarray(directory)]))).toEqual(acceptanceFixture)
  })
  it.each(['truncated', 'oversized', 'multiple', 'encrypted', 'symlink', 'traversal', 'bad_crc', 'zip_bomb', 'bad_offset', 'bad_descriptor'])('rejects %s archives', (kind) => {
    let archive = acceptanceArchive()
    const end = archive.length - 22
    const directory = archive.readUInt32LE(end + 16)
    if (kind === 'truncated') archive = archive.subarray(0, archive.length - 1)
    if (kind === 'oversized') archive = Buffer.alloc(MAX_ACCEPTANCE_ARCHIVE_BYTES + 1)
    if (kind === 'multiple') archive.writeUInt16LE(2, end + 10)
    if (kind === 'encrypted') archive.writeUInt16LE(1, directory + 8)
    if (kind === 'symlink') archive.writeUInt32LE(0xa0000000, directory + 38)
    if (kind === 'traversal') archive.write('../outside.txt', directory + 46)
    if (kind === 'bad_crc') archive.writeUInt32LE(0, directory + 16)
    if (kind === 'zip_bomb') archive.writeUInt32LE(100_000_000, directory + 24)
    if (kind === 'bad_offset') archive.writeUInt32LE(0xffffffff, end + 16)
    if (kind === 'bad_descriptor') { archive.writeUInt16LE(8, 6); archive.writeUInt16LE(8, directory + 8) }
    expect(() => readAcceptanceArchive(archive)).toThrow()
  })
})

describe('named acceptance proof identity', () => {
  const expected = { projectId: acceptanceFixture.projectId, sha: acceptanceFixture.sha, runId: 10, runAttempt: 1,
    startedAt: '2026-09-06T01:00:00.000Z', observedAt: '2026-09-06T01:06:00.000Z' }
  it('binds project, exact SHA, workflow run, attempt and time', () => {
    expect(acceptanceMatchesObservation(acceptanceFixture, expected)).toBe(true)
    for (const patch of [{ projectId: 'other' }, { sha: 'a'.repeat(40) }, { runId: 9 }, { runAttempt: 2 },
      { startedAt: '2026-09-06T01:06:00.000Z' }, { observedAt: '2026-09-06T01:00:00.000Z' }]) {
      expect(acceptanceMatchesObservation(acceptanceFixture, { ...expected, ...patch })).toBe(false)
    }
  })
  it('rejects skipped, duplicate and unbound reports', () => {
    for (const patch of [{ environment: 'production' }, { checks: [] }, { projectId: null }, { runAttempt: 0 },
      { checks: [...acceptanceFixture.checks, ...acceptanceFixture.checks] }, { criterionIds: ['same', 'same'] },
      { checks: [{ ...acceptanceFixture.checks[0], status: 'skipped' }] }]) {
      expect(acceptanceReportSchema.safeParse({ ...acceptanceFixture, ...patch }).success).toBe(false)
    }
  })
  it('never attaches another project/SHA or failed custom checks to green feedback', () => {
    const feedback = buildValidationFeedback({ projectId: expected.projectId, checkpointId: '22222222-2222-4222-8222-222222222222',
      commitSha: 'a'.repeat(40), publishedSha: expected.sha, checksSha: expected.sha, observedAt: expected.observedAt,
      required: ['Políticas RLS'], checks: [{ name: 'Políticas RLS', status: 'completed', conclusion: 'success' }], integrated: false, evidence: '' })
    expect(validationFeedbackSchema.safeParse({ ...feedback, acceptance: acceptanceFixture }).success).toBe(true)
    for (const patch of [{ sha: 'a'.repeat(40) }, { projectId: '33333333-3333-4333-8333-333333333333' },
      { checks: [{ ...acceptanceFixture.checks[0], status: 'failed' }] }]) {
      expect(validationFeedbackSchema.safeParse({ ...feedback, acceptance: { ...acceptanceFixture, ...patch } }).success).toBe(false)
    }
    expect(validationFeedbackSchema.parse(feedback).acceptance).toBeUndefined()
  })
})
