import { boundedJson } from '../database-inspection/provider'
import { DataDeleteError } from './contract'

export interface DeleteProvider {
  /** Accepts only SQL generated by this module's server, never user SQL. */
  query(sql: string, readOnly: boolean): Promise<unknown>
}

export function supabaseDeleteProvider(resolve: () => Promise<{ token: string; projectRef: string }>): DeleteProvider {
  return { async query(sql, readOnly) {
    const { token, projectRef } = await resolve()
    if (!/^[a-z0-9_-]{1,64}$/.test(projectRef)) throw new DataDeleteError('Vínculo do banco inválido.')
    let response: Response
    try {
      response = await fetch(`https://api.supabase.com/v1/projects/${projectRef}/database/query`, {
        method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
        body: JSON.stringify({ query: readOnly ? `BEGIN READ ONLY; SET LOCAL statement_timeout = '8s'; ${sql}; COMMIT;` : sql }),
        redirect: 'error', cache: 'no-store', signal: AbortSignal.timeout(20_000),
      })
    } catch {
      throw new DataDeleteError('O banco não confirmou o resultado no prazo. O plano de execução não será repetido; consulte os registros antes de preparar outro plano.', 504)
    }
    if (!response.ok) {
      let detail = ''
      try { detail = JSON.stringify(await boundedJson(response, 12_000)) } catch { /* Untrusted provider errors are never forwarded. */ }
      if (detail.includes('SUPREMO_DELETE_CHANGED') || detail.includes('SUPREMO_DELETE_COUNT'))
        throw new DataDeleteError('Os dados ou a estrutura mudaram desde a revisão. Nenhuma exclusão foi confirmada; prepare e confira outro plano.')
      if (detail.includes('SUPREMO_DELETE_DEPENDENCIES'))
        throw new DataDeleteError('Existem registros dependentes fora do plano. Confira o impacto antes de autorizar outro plano.')
      throw new DataDeleteError(`Exclusão não confirmada pelo banco (HTTP ${response.status}). Confira os registros e as dependências antes de repetir.`, response.status === 429 ? 429 : 409)
    }
    try { return await boundedJson(response, 400_000) }
    catch { throw new DataDeleteError('Resposta do banco inválida; resultado não confirmado. Consulte os registros antes de preparar outro plano.', 502) }
  } }
}
